### ISSUE TITLE
Some questions about qitmeer-wallet-rpc tutorial: inconsistent command

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/docs#50]
https://github.com/Qitmeer/docs/tree/master/Document/content/tutorials/qitmeer-wallet-rpc

文档中有几处命令与qitmeer-wallet console里的命令不一致：

- run ui

  ./qitmeer-wallet qc web，这里现在应该是  `./qitmeer-wallet web`

- 3.wallet_getAccountsAndBalance

  目前只有qitmeer-wallet qc命令里有一个 listaccountsbalance 可以实现同时获得账户和余额，console里缺少这个命令：既没有getAccountsAndBalance，也没有listAccountsBalance

- 6.wallet_createAddress {accountName}

  没有createAddress这个命令，实现同样功能的应该是 getNewAddress

- 7.wallet_sendToAddressByAccount

  没有sendToAddressByAccount命令，console里只有个sendToAddress，而且目前好像不支持使用指定账户里的money，也就是是byAccount功能，只有一个默认使用imported账户里的钱

- 8.wallet_getTxListByAddr

  这个命令应该是 getListTxByAddr

- 11.ui_openWallet 

  打开uiwallet，目前好像是用的`qitmeer-wallet web`，是否存在ui_openWallet 命令？

- 12.wallet_syncStats 和 wallet_getUtxo 这两个命令是否存在？在pc wallet的命令中未看到有类似命令

- 15.wallet_getBalanceByAddr

  目前实现此功能的，好像是 getBalance 命令，console中无 getBalanceByAddr 命令

- 16.wallet_sendToAddressBatch 

  此命令是不是在console中本身就没有，因为console中无法实现此功能，只存在于json形式的rpc接口中？

**Comment by forchain** [comment]
1.  separate  wallet command into independent folder
2. every command has the corresponding  cli, RPC, console usage
